server:
  port: 1885

spring:
  application:
    # 服务与服务之间相互调用一般都是根据这个name 。
    name: auth-service
  datasource:
    url: jdbc:mysql://10.10.10.166:3306:3306/rbac?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#    springboot2.0+默认为hikari 此配置项可删除
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 3
      auto-commit: true
      idle-timeout: 10000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

mybatis:
  mapper-locations: classpath:/mapper/*

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/