server:
  port: 1885

spring:
  application:
    # 服务与服务之间相互调用一般都是根据这个name 。
    name: auth-service
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 3
#      auto-commit: true
#      idle-timeout: 10000
#      pool-name: DatebookHikariCP
#      max-lifetime: 1800000
#      connection-timeout: 30000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/