server:
  port: 1990

eureka:
  client:
    serviceUrl:
      #      defaultZone: http://47.99.211.9:8761/eureka/
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: cms-service