eureka:
  client:
    serviceUrl:
#      defaultZone: http://47.99.211.9:8761/eureka/
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8762

spring:
  application:
    name: zuul-service

zuul:
  routes:
    rbac-api:
      path: /rbac-api/**
      serviceId: rbac-service
    cms-api:
      path: /cms-api/**
      serviceId: cms-service