server:
  port: 1880

spring:
  application:
    # 服务与服务之间相互调用一般都是根据这个name 。
    name: rbac-service

eureka:
  client:
    service-url:
#      defaultZone: http://47.99.211.9:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
